"""add harga_1 to pembelian_detail

Revision ID: 71bdcc288bd8
Revises: b3c1de845f20
Create Date: 2026-05-25 20:15:16.710107

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '71bdcc288bd8'
down_revision: Union[str, None] = 'b3c1de845f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pembelian_detail', sa.Column('harga_1', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pembelian_detail', 'harga_1')
    # ### end Alembic commands ###
