"""initial

Revision ID: a7b2bc743e59
Revises: 
Create Date: 2026-05-08 17:06:55.569496

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a7b2bc743e59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_kategori', sa.String(length=20), nullable=False),
    sa.Column('nama_kategori', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_kategori')
    )
    op.create_index(op.f('ix_kategori_id'), 'kategori', ['id'], unique=False)
    op.create_table('keuangan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kredit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keuangan_id'), 'keuangan', ['id'], unique=False)
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_toko', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('printer_port', sa.String(length=50), nullable=True),
    sa.Column('printer_width', sa.Integer(), nullable=True),
    sa.Column('receipt_footer', sa.String(length=255), nullable=True),
    sa.Column('tax_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_supplier', sa.String(length=20), nullable=False),
    sa.Column('nama_supplier', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('kontak', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_supplier')
    )
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('barang',
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('nama_barang', sa.String(length=150), nullable=False),
    sa.Column('id_kategori', sa.Integer(), nullable=True),
    sa.Column('sat', sa.String(length=20), nullable=False),
    sa.Column('hpp', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('harga_1', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('harga_2', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_qty_harga_2', sa.Integer(), nullable=False),
    sa.Column('harga_3', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_qty_harga_3', sa.Integer(), nullable=False),
    sa.Column('stok', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stok_minimum', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id'], ),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_index(op.f('ix_barang_barcode'), 'barang', ['barcode'], unique=False)
    op.create_index(op.f('ix_barang_nama_barang'), 'barang', ['nama_barang'], unique=False)
    op.create_table('pembelian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_faktur', sa.String(length=50), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('id_supplier', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_supplier'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pembelian_id'), 'pembelian', ['id'], unique=False)
    op.create_index(op.f('ix_pembelian_no_faktur'), 'pembelian', ['no_faktur'], unique=True)
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_transaksi', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bayar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kembalian', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_id'), 'transaksi', ['id'], unique=False)
    op.create_index(op.f('ix_transaksi_no_transaksi'), 'transaksi', ['no_transaksi'], unique=True)
    op.create_table('pembelian_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pembelian', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('nama_barang', sa.String(length=150), nullable=False),
    sa.Column('sat', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('hpp', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['barcode'], ['barang.barcode'], ),
    sa.ForeignKeyConstraint(['id_pembelian'], ['pembelian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pembelian_detail_id'), 'pembelian_detail', ['id'], unique=False)
    op.create_table('transaksi_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_transaksi', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('nama_barang', sa.String(length=150), nullable=False),
    sa.Column('sat', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('hpp', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('harga', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('diskon', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_transaksi'], ['transaksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_detail_id'), 'transaksi_detail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaksi_detail_id'), table_name='transaksi_detail')
    op.drop_table('transaksi_detail')
    op.drop_index(op.f('ix_pembelian_detail_id'), table_name='pembelian_detail')
    op.drop_table('pembelian_detail')
    op.drop_index(op.f('ix_transaksi_no_transaksi'), table_name='transaksi')
    op.drop_index(op.f('ix_transaksi_id'), table_name='transaksi')
    op.drop_table('transaksi')
    op.drop_index(op.f('ix_pembelian_no_faktur'), table_name='pembelian')
    op.drop_index(op.f('ix_pembelian_id'), table_name='pembelian')
    op.drop_table('pembelian')
    op.drop_index(op.f('ix_barang_nama_barang'), table_name='barang')
    op.drop_index(op.f('ix_barang_barcode'), table_name='barang')
    op.drop_table('barang')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_table('setting')
    op.drop_index(op.f('ix_keuangan_id'), table_name='keuangan')
    op.drop_table('keuangan')
    op.drop_index(op.f('ix_kategori_id'), table_name='kategori')
    op.drop_table('kategori')
    # ### end Alembic commands ###
